server:
  port: 9270
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/apihub?serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: 980729
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        enabled: true
